import datetime
from decimal import Decimal

person_1 = {'f_name': 'Валерия',
            's_name': 'Валерьевна',
            'surname': 'Дятел',
            'birthdate': datetime.date(2003, 1, 5),
            'sex': 'ж', 'passport_seria': 'МС',
            'passport_num': '1111111',
            'p_issued_by': 'несвижское ровд',
            'p_issued_date': datetime.date(2020, 6, 6),
            'p_ident_num': '111111A111AA1',
            'address_residence': 'солнечная 12',
            'home_number': '',
            'mobile_number': '',
            'e_mail': 'lerkadziatsel@gmail.com',
            'city': 'Гомель',
            'mat_stat': '1',
            'citizenship_name': 'Россия',
            'disability': '1',
            'pensioner': True,
            'amount': Decimal('5000.55'),
            'military_duty': False}

person_2 = {'f_name': 'Надежда',
            's_name': 'Петровна',
            'surname': 'Иванова',
            'birthdate': datetime.date(2003, 1, 5),
            'sex': 'ж', 'passport_seria': 'МС',
            'passport_num': '2222222',
            'p_issued_by': 'несвижское ровд',
            'p_issued_date': datetime.date(2020, 6, 6),
            'p_ident_num': '2222222E222EE2',
            'address_residence': 'солнечная 34',
            'home_number': '',
            'mobile_number': '375291234567',
            'e_mail': '',
            'city': 'Минск',
            'mat_stat': '2',
            'citizenship_name': 'Казахстан',
            'disability': '2',
            'pensioner': False,
            'amount': Decimal('5000.55'),
            'military_duty': False}


person_3 = {'f_name': 'Иван',
            's_name': 'Иванович',
            'surname': 'Иванов',
            'birthdate': datetime.date(1993, 1, 5),
            'sex': 'ж', 'passport_seria': 'ПС',
            'passport_num': '3333333',
            'p_issued_by': 'Миснкое ровд',
            'p_issued_date': datetime.date(2017, 6, 6),
            'p_ident_num': '3333333D333DD3',
            'address_residence': 'Куйбышева 18',
            'home_number': '801745383',
            'mobile_number': '',
            'e_mail': 'ivanov@gmail.com',
            'city': 'Брест',
            'mat_stat': '3',
            'citizenship_name': 'Беларусь',
            'disability': '1',
            'pensioner': False,
            'amount': None,
            'military_duty': False}

person_4 = {'f_name': 'Иван',
            's_name': 'Иванович',
            'surname': 'Иванов',
            'birthdate': datetime.date(1993, 1, 5),
            'sex': 'ж', 'passport_seria': 'РТ',
            'passport_num': '4444444',
            'p_issued_by': 'Миснкое ровд',
            'p_issued_date': datetime.date(2017, 6, 6),
            'p_ident_num': '4444444G444GG4',
            'address_residence': 'Куйбышева 18',
            'home_number': '',
            'mobile_number': '',
            'e_mail': '',
            'city': 'Брест',
            'mat_stat': '3',
            'citizenship_name': 'Беларусь',
            'disability': '1',
            'pensioner': False,
            'amount': None,
            'military_duty': False}


person_5 = {'f_name': 'Петр',
            's_name': 'Петрович',
            'surname': 'Петров',
            'birthdate': datetime.date(1973, 1, 5),
            'sex': 'ж', 'passport_seria': 'КТ',
            'passport_num': '5555555',
            'p_issued_by': 'Миснкое ровд',
            'p_issued_date': datetime.date(2020, 4, 6),
            'p_ident_num': '5555555G555GG5',
            'address_residence': 'Куйбышева 55',
            'home_number': '801755555',
            'mobile_number': '375445555555',
            'e_mail': 'petr@mail.ru',
            'city': 'Брест',
            'mat_stat': '3',
            'citizenship_name': 'Казахстан',
            'disability': '1',
            'pensioner': True,
            'amount': None,
            'military_duty': True}


person_list = [person_1, person_2, person_3, person_4, person_5]